clear_output: true
force_cpu: false
frame_buffer_size: 4
live_cam_start_active: false
max_threads: 10
memory_limit: 0
output_image_format: png
output_video_codec: libx264
output_video_format: mp4
provider: cuda
selected_theme: Default
server_name: ""
server_port: 0
server_share: false
video_quality: 14
